[package]
name = "bip-39-solver-cpu"
version = "0.0.1"
authors = ["johncantrell97"]
edition = "2018"

[dependencies]
sha2 = "0.8.2"
rayon = "1.3.0"
ring = "0.16"
bitcoin-wallet = { git = "https://github.com/johncantrell97/rust-wallet" }
